services:
  web:
    image: gavinlon/magic-stream-web:${IMAGE_TAG:-latest}
    ports: 
      - "5173:80"
    restart: always

  api:
    image: gavinlon/magic-stream-api:${IMAGE_TAG:-latest}
    restart: always
